MySQL:
  Host: localhost:3306
  DataBase: "minecraft"
  User: "root"
  Password: "OBXq94zQCX4SgEmM"

BlackListWorld:
  - "world"

Permission: "CLhome."
NoPermission: "&cVocê não tem permissão."
MinimumCharactersHome: "3"
Delay: "3" #in seconds
DelayFromOtherTeleport: "3" #in seconds

Message:
  #SetHome
  SetHomeArgumentsInvalid: "&cArgumentos invalidos."
  BlackListWorldMessage: "&cNão é possivel setar uma home nesse mundo."
  HomeLimitReached: "&cVocê já possui o numero máximo de Homes."
  FewCharacters: "&cSua Home precisa ter mais do que 3 caracteres."
  ContainsHome: "&cVocê já contem uma home com esse nome."
  HomeSucessCreate: "&cHome setada com sucesso."
  #DelHome
  DelHomeArgumentsInvalid: "&cArgumentos invalidos."
  DelHomeNotFound: "&cVocê não tem nenhuma home com esse nome."
  HomeSucessDeleted: "&cHome deletada com sucesso."
  #Home
  HomeInvalidArgument: "&cArgumentos invalidos."
  HomeNotFound: "&cVocê não tem nenhuma home com esse nome."
  DelayMessage: "&cAguarde %delay% segundos para executar esse comando novamente."
  MessageWaitingTeleport:
    Title: "&cVocê será teleportado em"
    SubTitle: "&f%delay% segundos."
  MessageSucessTeleport:
    Title: "&cVocê foi teleportado para"
    SubTitle: "&fHome %home% - #%number%"
  MessageCancelTeleport:
    Title: "&cVocê se moveu"
    SubTitle: "&fenquanto estava em teleporte"
Sounds: #All MineCraft Sounds - https://helpch.at/docs/1.8.8/index.html?org/bukkit/Sound.html
  SoundWaitingTeleport: "ORB_PICKUP"
  SoundSucessTeleport: "ENDERMAN_TELEPORT"
  SoundCancelTeleport: "VILLAGER_NO"

Inventory: #Home - GUI
  Title: "&7All Homes - %player%"
  HomeTemplate:
    Name: "Homes #%number% - %home%"
    Material: "DARK_OAK_DOOR_ITEM"
    Data: "0"
    Glow: "True"
    Lore:
      - ""
    Enchantment:
      - "UNBREAKING:10"
  CustomInventory:
    InfoHomes:
      Slot: "5"
      Amount: "1"
      Material: "EMERALD"
      Data: "0"
      Name: "Homes Of %player% - %amounthomes%/%maxhomes%"
      Glow: "True"
      Lore:
        - "%player%"
      Enchantment:
        - "UNBREAKING:10"