#Permissions:
# Clhome.(Number) = Homes Limit
# Clhome.admin = All Permissions
# Clhome.bypass = Bypass Delay Teleport
# Clhome.otherteleportbypass = Bypass Cooldown Teleport

MySQL:
  Host: localhost:3306
  DataBase: "minecraft"
  User: "root"
  Password: "OBXq94zQCX4SgEmM"

BlackListWorld:
  - "world"

Permission: "Clhome."
NoPermission: "&3CelesteHomes &7You not a have Permission"
MinimumCharactersHome: "3"
Delay: "3" #in seconds
DelayFromOtherTeleport: "3" #in seconds

Message:
  #SetHome
  SetHomeArgumentsInvalid: "&3CelesteHomes &7Invalid arguments."
  BlackListWorldMessage: "&3CelesteHomes &7Isn't possible to set a home in this world."
  HomeLimitReached: "&3CelesteHomes &7You already have the maximum number of Homes."
  FewCharacters: "&3CelesteHomes &7Your Home must be longer than 3 characters."
  ContainsHome: "&3CelesteHomes &7You already have a home with that name."
  HomeSucessCreate: "&3CelesteHomes &7Home set successfully."
  #DelHome
  DelHomeArgumentsInvalid: "&3CelesteHomes &7Invalid arguments."
  DelHomeNotFound: "&3CelesteHomes &7You don't have a Home with that name."
  HomeSucessDeleted: "&3CelesteHomes &7Home successfully deleted."
  #Home
  HomeInvalidArgument: "&3CelesteHomes &7Invalid arguments."
  HomeNotFound: "&3CelesteHomes &7You don't have a Home with that name."
  DelayMessage: "&3CelesteHomes &7Wait &f%delay% seconds &7to run this command again."
  MessageWaitingTeleport:
    Title: "&fYou will be teleported in"
    SubTitle: "&c%delay% seconds"
  MessageSucessTeleport:
    Title: "&fYou have been teleported to"
    SubTitle: "&cHome %home% - #%number%"
  MessageCancelTeleport:
    Title: "&cYou moved"
    SubTitle: "&cWhile teleporting"
Sounds: #All MineCraft Sounds - https://helpch.at/docs/1.8.8/index.html?org/bukkit/Sound.html
  SoundWaitingTeleport: "ORB_PICKUP"
  SoundSucessTeleport: "ENDERMAN_TELEPORT"
  SoundCancelTeleport: "VILLAGER_NO"

Inventory: #Home - GUI
  Title: "&7All Homes - %player%"
  HomeTemplate:
    Name: "Homes #%number% - %home%"
    Material: "DARK_OAK_DOOR_ITEM"
    Data: "0"
    Glow: "True"
    Lore:
      - ""
    Enchantment:
      - "UNBREAKING:10"
  CustomInventory:
    InfoHomes:
      Slot: "4"
      Amount: "1"
      Material: "EMERALD"
      Data: "0"
      Name: "Homes Of %player% - %amounthomes%/%maxhomes%"
      Glow: "True"
      Lore:
        - "%player%"
      Enchantment:
        - "UNBREAKING:10"