MySQL:
  Use: false
  Host: "localhost:3306"
  DataBase: ""
  User: ""
  Password: ""

Admin_Permission: "celesteshop.admin"
NoPermission: "&b&lSHOP &7You not a have permission."

Inventory:
  Title: "&8SHOP - CATEGORIES"
  Size: 54
  ItemsDecoration:
    Information:
      Slot: 4
      Amount: 1
      Material: "EMERALD"
      Data: 0
      Name: "&bYou a have &f%points% &bpoints"
      Glow: true
      Lore:
        - ""
        - "                 &f&lTERMS"
        - "&6> &7You will not be able to ask for"
        - "&7a refund of the product just to buy."
        - "&6> &7Purchased items and benefits can"
        - "&7be suspended and withdrawn at any time"
        - "&7without notice."
      Enchantment: []

InventoryConfirm:
  Title: "SHOP - CONFIRM BUY"
  Size: 45
  Confirm:
    Slot: 24
    Amount: 1
    Material: "WOOL"
    Data: 5
    Name: "&aAccept"
    Glow: false
    Lore:
      - "&7Click to accept"
      - "&7the purchase."
    Enchantment: []

  Reject:
    Slot: 20
    Amount: 1
    Material: "WOOL"
    Data: 14
    Name: "&4Deny"
    Glow: false
    Lore:
      - "&7Click to deny"
      - "&7the purchase."
    Enchantment: []

  ItemTemplate:
    Use: true
    Slot: 4

  ItemsDecoration:
    Information:
      Slot: 22
      Amount: 1
      Material: "PAPER"
      Data: 0
      Name: "&f&lTERMS"
      Glow: true
      Lore:
        - ""
        - "&6> &7You will not be able to ask for"
        - "&7a refund of the product just to buy."
        - "&6> &7Purchased items and benefits can"
        - "&7be suspended and withdrawn at any time"
        - "&7without notice."
      Enchantment: []