MySQL:
  Host: localhost
  DataBase: "minecraft"
  User: "root"
  Password: "OBXq94zQCX4SgEmM"

Menu:
  Title: "Rede Celeste - SHOP"
  Rows: 6
  InsufficientCash: "&cVocê não tem Cashs suficientes."

Shop:
  L8:
    Material: "DIAMOND_SWORD"
    Data: 0
    Amount: 1
    Name: "&7Compre essa espada looting 8"
    Lore:
    - "&7ABLUBLÉ"
    - "&7BLUBLUBLÉ"
    Enchantament:
    - "DAMAGE_ALL:10"
    - "KNOCKBACK:3"
    Price: 10
    Command: "tell %player% Olá"
    Slot: 22
    BuyMessage:
      Title: "&7Você comprou"
      SubTile: "&7uma espada Looting 8"
      ActionBarMessage: "&6Muito obrigado pela compra"