MySQL: # MySQL Storage
  # Enables / Disables storage by MySQL
  Use: false
  # The MySQL server IP
  Host: "localhost:3306"
  # The name of the database that will be stored in the table
  DataBase: ""
  # The MySQL login username
  User: ""
  # The MySQL password
  Password: ""

Permission: # All permissions (The permission name refers to the command it answers)
  # Administrator permission (Contains all permissions bellow)
  Admin: "essentials.admin"
  Anvil: "essentials.anvil"
  BroadCast: "essentials.bc"
  Burn: "essentials.burn"
  Clear: "essentials.clear"
  Clear-Other-Players: "essentials.clear.other"
  Compact: "essentials.compact"
  Craft: "essentials.craft"
  Crash: "essentials.crash"
  Effect: "essentials.effect"
  Enchant: "essentials.enchant"
  Exp: "essentials.exp"
  Fly: "essentials.fly"
  Fly-Other-Players: "essentials.fly.other"
  Food: "essentials.food"
  Food-Other-Players: "essentials.food.other"
  Gamemode: "essentials.gm"
  Gamemode-Other-Players: "essentials.gm.other"
  GC: "essentials.gc"
  Give: "essentials.give"
  God: "essentials.god"
  God-Other-Players: "essentials.god.other"
  Hat: "essentials.hat"
  Head: "essentials.head"
  Heal: "essentials.heal"
  Heal-Other-Players: "essentials.heal.other"
  Jump: "essentials.jump"
  Kill: "essentials.kill"
  Kill-Other-Players: "essentials.kill.other"
  Lightning: "essentials.lightning"
  Lore: "essentials.lore"
  More: "essentials.more"
  Name: "essentials.name"
  Potion: "essentials.potion"
  PowerTool: "essentials.powertool"
  Reload: "essentials.reloadWarp"
  Repair: "essentials.repair"
  Speed: "essentials.speed"
  Sudo: "essentials.sudo"
  Teleport: "essentials.tp"
  Teleport-Bypass-Delay: "essentials.delay.bypass"
  TeleportHere: "essentials.tphere"
  Time: "essentials.time"
  Top: "essentials.top"
  Warp: "essentials.warp"
  Whois: "essentials.whois"

Sounds: # All MineCraft Sounds - https://helpch.at/docs/1.8.8/index.html?org/bukkit/Sound.html
  # Sound which will be sent if the player teleport success
  Teleport: "ENDERMAN_TELEPORT"
  # Sound which will be sent if the player is in the teleport delay
  Delay: "ORB_PICKUP"
  # Sound which will be sent if the player move on teleport
  Move: "VILLAGER_NO"

Commands: # Custom Commands
  Site: # Just any name
    # Command which will has to be executed
    Command: "site"
    # Message which will send
    Message:
      - ""
      - "&7WebSite: &6https://google.com"
      - ""

Inventory-Warp: # Inventory Warp System
  # Title menu
  Title: "&8Warps"
  # Size menu
  Size: 54
  Decoration: # Items that have no function, only decorative
    Information: # Just any name
      # The position of the item in the menu
      Slot: 4
      # The coins of item
      Amount: 1
      # The material of the item
      Material: ""
      # The material date of the item
      Data: 0
      # The name of the item
      #
      # Placeholders:
      # {player} - Player name
      Name: "&6Warps"
      # Enables / Disables The glow in the item
      Glow: true
      # The lore of the item
      #
      # Placeholders:
      # {player} - Player name
      Lore: []
      # The enchantment in the item (Remember if you want to disable the glow) - (All Minecraft enchants https://ghostbin.co/paste/w2ttacs)
      Enchantment: []
      Head: # Head drop system
        # Enables / Disables The head system
        Use: true
        # The texture of the head (These heads will be the Minecraft textures URL code) - (If it is null it will be the head of the mob)
        Texture: "16439d2e306b225516aa9a6d007a7e75edd2d5015d113b42f44be62a517e574f"

Inventory-Trash: # Inventory Trash System
  # Title menu
  Title: "&8Trash"
  # Size menu
  Size: 45

Teleport: # Teleport System
  # Delay to player complete teleport
  Delay: 3
  # Teleportation must be canceled when the player moves
  Cancel-On-Move: false